### DISCUSSION TITLE
Possible To Configure Default BootTimeout Via Docker Compose?

### DISCUSSION THREAD

**Discussion by irishgordo** [antonym/netboot.xyz#1460] [Q&A]
Hi all!
Hope the week has been stellar for everyone!
This project is rad!

I was curious, if I have docker compose, compose.yaml that takes the shape of:
```yaml
---
version: "2.1"
services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    environment:
      - PUID=1000 #current user
      - PGID=1000 #current group
      - TZ=Etc/UTC
      # - MENU_VERSION=1.9.9 #optional, sets menus version, unset uses latest
      - PORT_RANGE=30000:30010 #optional
      - SUBFOLDER=/ #optional
    volumes:
      - ./config:/config
      - ./assets:/assets #optional
    ports:
      - 3000:3000
      - 69:69/udp
      - 8080:80 #optional
    restart: unless-stopped
```

I'm wondering if there's any way to set the:
- https://github.com/netbootxyz/netboot.xyz/blob/471bc898cc474eeb22951182844d2dbe7f0c8dcb/roles/netbootxyz/templates/menu/boot.cfg.j2#L26
- https://github.com/netbootxyz/netboot.xyz/blob/471bc898cc474eeb22951182844d2dbe7f0c8dcb/roles/netbootxyz/templates/menu/menu.ipxe.j2#L128-L130
- Disabling, (setting to false, by default): https://github.com/netbootxyz/netboot.xyz/blob/471bc898cc474eeb22951182844d2dbe7f0c8dcb/roles/netbootxyz/templates/menu/menu.ipxe.j2#L120-L122

Both the timeout ,the custom github handle alongside disabling the signature check at the start up of netbootxyz's default `menu.ipxe`? 

The github handle is super useful!
Really appreciate the convention of forking:
https://github.com/netbootxyz/netboot.xyz-custom

Maybe some sort of override?
Hopefully without fully customizing the menu?

Something where `docker compose up -d` would just funnel in the changes.

Thanks for any input / info! :+1: :100:
